"""Add insurance and financial class fields to claims table

Revision ID: 9c0d1e2f3a4b
Revises: 8b9c0d1e2f3a
Create Date: 2024-04-01 12:05:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0d1e2f3a4b'
down_revision = '8b9c0d1e2f3a' # Previous migration (modify_claims_for_encryption)
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('financial_class', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_claims_financial_class'), 'claims', ['financial_class'], unique=False)

    op.add_column('claims', sa.Column('insurance_type', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_claims_insurance_type'), 'claims', ['insurance_type'], unique=False)

    op.add_column('claims', sa.Column('insurance_plan_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_claims_insurance_plan_id'), 'claims', ['insurance_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_insurance_plan_id'), table_name='claims')
    op.drop_column('claims', 'insurance_plan_id')

    op.drop_index(op.f('ix_claims_insurance_type'), table_name='claims')
    op.drop_column('claims', 'insurance_type')

    op.drop_index(op.f('ix_claims_financial_class'), table_name='claims')
    op.drop_column('claims', 'financial_class')
    # ### end Alembic commands ###
